# Generated by Django 4.2.3 on 2024-04-03 00:52

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('gym', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='plan',
            name='price',
            field=models.IntegerField(default=12),
            preserve_default=False,
        ),
    ]
